# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'buywine', '0001_initial'), (b'buywine', '0002_auto_20180918_0634'), (b'buywine', '0003_auto_20180918_0638'), (b'buywine', '0004_auto_20180918_0646')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('country_abbrev', models.CharField(max_length=10, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country_name'],
                'db_table': 'country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=255)),
                ('province_abbrev', models.CharField(max_length=40)),
                ('visible', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Country')),
            ],
            options={
                'ordering': ['country', 'province_name'],
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('region_abbrev', models.CharField(max_length=40)),
                ('visible', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Country')),
            ],
            options={
                'ordering': ['country', 'region_name'],
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=255)),
                ('state_abbrev', models.CharField(blank=True, max_length=40)),
                ('viaible', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Country')),
            ],
            options={
                'ordering': ['country', 'state_name'],
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal_name', models.CharField(default=b'', max_length=255, unique=True)),
                ('varietal_desc', models.TextField(blank=True, default=b'', null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['varietal_name'],
                'db_table': 'varietal',
            },
        ),
        migrations.CreateModel(
            name='Vineyard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vineyard_name', models.CharField(max_length=255, unique=True)),
                ('vineyard_location_desc', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('vineyard_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.Address')),
            ],
            options={
                'ordering': ['vineyard_name'],
                'db_table': 'vineyard',
            },
        ),
        migrations.CreateModel(
            name='VineyardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=b'')),
                ('comment_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vineyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Vineyard')),
            ],
            options={
                'ordering': ['vineyard', 'comment_date'],
                'db_table': 'vineyard_comments',
            },
        ),
        migrations.CreateModel(
            name='Vintner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, default=b'', max_length=255)),
                ('first_name', models.CharField(default=b'', max_length=255)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'db_table': 'vintner',
            },
        ),
        migrations.CreateModel(
            name='VintnerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=b'')),
                ('comment_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vintner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Vintner')),
            ],
            options={
                'ordering': ['vintner', 'comment_date'],
                'db_table': 'vintner_comments',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage_type', models.CharField(choices=[(b'S', b'Single Year'), (b'M', b'Mixed Vintage')], max_length=1)),
                ('vintage_year', models.IntegerField()),
                ('num_bottles', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_updated_by', to=settings.AUTH_USER_MODEL)),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Varietal')),
                ('vineyard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.Vineyard')),
                ('vintner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.Vintner')),
            ],
            options={
                'ordering': ['varietal', 'vintage_year', 'winery'],
                'db_table': 'wine',
            },
        ),
        migrations.CreateModel(
            name='WineComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=b'')),
                ('comment_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Wine')),
            ],
            options={
                'ordering': ['wine', 'comment_date'],
                'db_table': 'wine_comments',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winery_name', models.CharField(max_length=255, unique=True)),
                ('winery_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('winery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.Address')),
            ],
            options={
                'ordering': ['winery_name'],
                'db_table': 'winery',
                'verbose_name_plural': 'Wineries',
            },
        ),
        migrations.CreateModel(
            name='WineryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=b'')),
                ('comment_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Winery')),
            ],
            options={
                'ordering': ['winery', 'comment_date'],
                'db_table': 'winery_comments',
            },
        ),
        migrations.CreateModel(
            name='WineryVintner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Vintner')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Winery')),
            ],
            options={
                'ordering': ['winery', 'vintner'],
                'db_table': 'map_winery_vintner',
            },
        ),
        migrations.CreateModel(
            name='WineServed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_description', models.TextField(blank=True, null=True)),
                ('num_bottles', models.IntegerField(blank=True, default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Wine')),
            ],
            options={
                'ordering': ['wine', 'event_date'],
                'db_table': 'wine_served',
                'verbose_name_plural': 'Wine Served',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Winery'),
        ),
        migrations.AlterUniqueTogether(
            name='vintner',
            unique_together=set([('last_name', 'first_name')]),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buywine.State'),
        ),
        migrations.AlterUniqueTogether(
            name='wineryvintner',
            unique_together=set([('winery', 'vintner')]),
        ),
        migrations.AlterUniqueTogether(
            name='wine',
            unique_together=set([('varietal', 'winery', 'vineyard', 'vintage_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('state_name', 'country'), ('state_abbrev', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('region_name', 'country'), ('region_abbrev', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together=set([('province_abbrev', 'country'), ('province_name', 'country')]),
        ),
        migrations.AlterModelTable(
            name='wine',
            table='wt_wine',
        ),
        migrations.AlterModelTable(
            name='address',
            table='wt_address',
        ),
        migrations.AlterModelTable(
            name='country',
            table='wt_country',
        ),
        migrations.AlterModelTable(
            name='province',
            table='wt_province',
        ),
        migrations.AlterModelTable(
            name='region',
            table='wt_region',
        ),
        migrations.AlterModelTable(
            name='state',
            table='wt_state',
        ),
        migrations.AlterModelTable(
            name='varietal',
            table='wt_varietal',
        ),
        migrations.AlterModelTable(
            name='vineyard',
            table='wt_vineyard',
        ),
        migrations.AlterModelTable(
            name='vineyardcomment',
            table='vineyard_comments',
        ),
        migrations.AlterModelTable(
            name='vintner',
            table='wt_vintner',
        ),
        migrations.AlterModelTable(
            name='vintnercomment',
            table='wt_vintner_comments',
        ),
        migrations.AlterModelTable(
            name='winecomment',
            table='wt_wine_comments',
        ),
        migrations.AlterModelTable(
            name='winery',
            table='wt_winery',
        ),
        migrations.AlterModelTable(
            name='winerycomment',
            table='wt_winery_comments',
        ),
        migrations.AlterModelTable(
            name='wineryvintner',
            table='wt_map_winery_vintner',
        ),
        migrations.AlterModelTable(
            name='wineserved',
            table='wt_wine_served',
        ),
    ]
