# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buywine', '0002_auto_20180918_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['wine', 'date_purchased', 'price'],
                'db_table': 'wt_bottle',
            },
        ),
        migrations.RemoveField(
            model_name='wine',
            name='num_bottles',
        ),
        migrations.AddField(
            model_name='wine',
            name='residual_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='sweet_or_dry',
            field=models.CharField(blank=True, choices=[(b'S', b'Sweet'), (b'SS', b'Semi-Sweet'), (b'SD', b'Semi-Dry'), (b'D', b'Dry')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buywine.Wine'),
        ),
    ]
