# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buywine', '0003_auto_20180918_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sweet_or_dry',
            field=models.CharField(blank=True, choices=[(b'SWT', b'Sweet'), (b'SSWT', b'Semi-Sweet'), (b'SDRY', b'Semi-Dry'), (b'DRY', b'Dry'), (b'DSRT', b'Dessert')], max_length=4, null=True),
        ),
    ]
